### ISSUE TITLE
domain TTL is 20 seconds

### ISSUE THREAD

**Issue by jshepin** [stevenson-space/shs#72]
I noticed that the domain has a TTL of 20 seconds. I'm not sure why it's so low, but I think it should be around 1 week (604, 800 seconds). Let me know if you have any thoughts on this. 

<img width="1280" alt="Screen Shot 2021-07-21 at 10 19 10 PM" src="https://user-images.githubusercontent.com/31457361/126585660-002fa15f-164c-42b4-bb8e-b2534b57e2b2.png">

**Comment by abhinavpappu** [comment]
Hmm, we're using Netlify for DNS as well (which I believe internally uses NS1) and it currently seems to be set to 1 hour. Any reason why we would want 1 week for the TTL? From my (very limited) understanding, I think a lower TTL is better in general so that any changes we make get propagated through faster, though it does mean the site might load marginally slower sometimes since records aren't cached for as long.

I've also used Cloudflare before for DNS, and it defaults to a TTL of 5 minutes when you select `Auto`, so I think having a low TTL is not too much of a concern, but let me know if you have any other thoughts!

**Comment by jshepin** [comment]
reason for 1 week in particular. A lower TTL would propagate changes faster, but probably does slow the site down a bit. 1 week is too much, maybe a day? 6 hrs?

I am wondering why the DNS server returns 19 seconds instead of the 5 minutes (or what it's set to). 

I use google's tool to lookup DNS information: https://toolbox.googleapps.com/apps/dig/#A/

**Comment by Chaldron** [comment]
I usually run super low TTLs when bringing up new sites since there are lots of rapid hosting/DNS changes, but we've been using the same domain, DNS record set, etc. for a couple years now. I wouldn't mind updating it to a day, I don't know exactly how much of a performance gain it could be but it probably wouldn't hurt.

**Comment by Chaldron** [comment]
I actually just took a look, and we seem to have a TTL of 60 minutes on the main domain, and 1 minute on the email domains. These values are all set in the Netlify DNS panel. Since it's managed by them, maybe they have their own custom setup or something which in reality results to a much lower TTL?
