### ISSUE TITLE
Fix events scraper

### ISSUE THREAD

**Issue by abhinavpappu** [stevenson-space/shs#74]
Currently, when running the events scraper, I'm getting the following error message:
![image](https://user-images.githubusercontent.com/22779056/128459375-67e745d6-7fb7-4eb3-a217-f8187d53dbe7.png)
even though when I manually try to access https://www.d125.org/data/calendar/icalcache/feed_AF5167036E214C99B84D252995DB9199.ics in the browser, it works fine.

For now, I temporarily disabled the events script to prevent Netlify build errors, will look into this soon. @jshepin @Chaldron can either of you also try running the pre build script locally? Might just be something wrong with my computer

**Comment by Chaldron** [comment]
I remember this happened a few years ago when I was trying to scrape the calendar events. IIRC there was a special token you had to include in a cookie or something in order to get access to the site. Or maybe user-agent string, I forgot exactly what it was. I can look into it and see if it's the same issue, but I think that's why it works on browser but not when scraping.
